function Hd = lowpassbutter
%LOWPASSBUTTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.1 and DSP System Toolbox 24.1.
% Generated on: 01-Jun-2024 22:12:57

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = 1000;  % Sampling Frequency

Fpass = 40;          % Passband Frequency
Fstop = 45;          % Stopband Frequency
Apass = 1;           % Passband Ripple (dB)
Astop = 40;          % Stopband Attenuation (dB)
match = 'stopband';  % Band to match exactly


Ws = Fstop/500;
Wp = Fpass/500;
Rp = Apass;
Rs = Astop;
[n,Wn] = buttord(Wp,Ws,Rp,Rs);
n = n * 2;
fprintf('Butterworth Order: %d\n', n)

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
